mini_4wd_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Velocity Controllers ----速度控制器---------------------
mini_4wd_left_front_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_front_wheel_joint
mini_4wd_right_front_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_front_wheel_joint
mini_4wd_left_rear_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_rear_wheel_joint
mini_4wd_right_rear_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_rear_wheel_joint